"""CAD Design Intelligence — Streamlit dashboard (generated by the notebook)."""
import json

import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
parts = pd.read_csv(ROOT / "data" / "cad_parts_clean.csv")
rework = pd.read_csv(ROOT / "data" / "manufacturing_rework.csv")
coefs = json.loads((ROOT / "data" / "model_coefficients.json").read_text())

st.set_page_config(page_title="CAD Design Intelligence", page_icon="⚙️", layout="wide")

st.markdown(
    """
    <style>
    .kpi { background: linear-gradient(135deg, #1f2a44 0%, #2b3a5e 100%);
           border-radius: 12px; padding: 16px 18px; color: white;
           box-shadow: 0 2px 8px rgba(0,0,0,.25); }
    .kpi .label { font-size: 12px; opacity: .75; text-transform: uppercase; letter-spacing: 1px; }
    .kpi .value { font-size: 28px; font-weight: 700; margin-top: 4px; }
    .kpi .sub { font-size: 12px; opacity: .65; margin-top: 2px; }
    </style>
    """,
    unsafe_allow_html=True,
)

rw_agg = (
    rework.groupby("part_id")
    .agg(events=("rework_id", "size"), cost=("rework_cost_usd", "sum"))
    .reset_index()
)
df = parts.merge(rw_agg, on="part_id", how="left").fillna({"events": 0, "cost": 0})
df["reworked"] = (df["events"] > 0).astype(int)


def score_part(row):
    """Rework probability from the notebook's fitted logistic coefficients."""
    feat = {
        "revision_count": float(row["revision_count"]),
        "num_features": float(row["num_features"]),
        "log_mass": float(np.log1p(row["mass_kg"])),
    }
    for col in coefs["feature_order"]:
        feat.setdefault(col, 0.0)
    for prefix, val in [
        ("tolerance_class_", row["tolerance_class"]),
        ("material_", row["material"]),
        ("part_category_", row["part_category"]),
        ("designer_team_", row["designer_team"]),
    ]:
        key = prefix + str(val)
        if key in feat:
            feat[key] = 1.0
    z = coefs["intercept"] + sum(coefs["features"][k] * feat[k] for k in coefs["feature_order"])
    return float(1 / (1 + np.exp(-z))), feat


def drivers(feat, top=5):
    contrib = {k: coefs["features"][k] * feat[k] for k in coefs["feature_order"] if feat[k] != 0}
    s = pd.Series(contrib).sort_values(ascending=False).head(top)
    nice = (
        s.index.str.replace("tolerance_class_", "tol=")
        .str.replace("material_", "mat=")
        .str.replace("part_category_", "cat=")
        .str.replace("designer_team_", "team=")
    )
    return pd.DataFrame({"driver": nice.values, "contribution": s.values})


st.title("⚙️ CAD Design Intelligence")
st.caption("From design metadata to rework prediction — what the CAD library says about shop-floor cost.")

with st.sidebar:
    st.header("Filters")
    tol = st.multiselect("Tolerance class", sorted(df["tolerance_class"].unique()),
                         default=sorted(df["tolerance_class"].unique()))
    cat = st.multiselect("Part category", sorted(df["part_category"].unique()),
                         default=sorted(df["part_category"].unique()))
fdf = df[df["tolerance_class"].isin(tol) & df["part_category"].isin(cat)]

tab1, tab2, tab3, tab4 = st.tabs(
    ["📊 Overview", "🎯 Part risk scorer", "🔍 Tolerance explorer", "🔥 Churn leaderboard"]
)

with tab1:
    k1, k2, k3, k4 = st.columns(4)
    for col, label, value, sub in [
        (k1, "Parts in library", f"{len(fdf):,}", "after DQ quarantine"),
        (k2, "Rework rate", f"{fdf['reworked'].mean():.1%}", f"{int(fdf['reworked'].sum()):,} parts affected"),
        (k3, "Rework events", f"{int(fdf['events'].sum()):,}", "shop-floor log"),
        (k4, "Total rework cost", f"${fdf['cost'].sum():,.0f}", "recoverable with design rules"),
    ]:
        col.markdown(
            f'<div class="kpi"><div class="label">{label}</div>'
            f'<div class="value">{value}</div><div class="sub">{sub}</div></div>',
            unsafe_allow_html=True,
        )
    st.write("")
    c1, c2 = st.columns(2)
    with c1:
        by_tol = fdf.groupby("tolerance_class")["reworked"].mean().reset_index()
        fig = px.bar(by_tol, x="tolerance_class", y="reworked", color="reworked",
                     color_continuous_scale="Reds", title="Rework rate by tolerance class",
                     labels={"reworked": "rework rate", "tolerance_class": ""})
        fig.update_layout(showlegend=False, yaxis_tickformat=".0%")
        st.plotly_chart(fig, use_container_width=True)
    with c2:
        by_rc = rework["root_cause"].value_counts().reset_index()
        by_rc.columns = ["root_cause", "events"]
        fig = px.bar(by_rc, x="events", y="root_cause", orientation="h", color="events",
                     color_continuous_scale="Blues", title="Rework events by root cause",
                     labels={"root_cause": "", "events": "events"})
        fig.update_layout(showlegend=False, yaxis={"categoryorder": "total ascending"})
        st.plotly_chart(fig, use_container_width=True)
    monthly_cost = rework.copy()
    monthly_cost["month"] = pd.to_datetime(monthly_cost["rework_date"]).dt.to_period("M").astype(str)
    mc = monthly_cost.groupby("month")["rework_cost_usd"].sum().reset_index()
    fig = px.area(mc, x="month", y="rework_cost_usd", title="Rework cost per month",
                  labels={"month": "", "rework_cost_usd": "USD"})
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    pid = st.selectbox("Select a part", sorted(df["part_id"].unique()))
    row = df[df["part_id"] == pid].iloc[0]
    proba, feat = score_part(row)
    c1, c2 = st.columns([1, 2])
    with c1:
        st.metric("Rework probability", f"{proba:.1%}")
        st.progress(min(max(proba, 0.0), 1.0))
        band = "🔴 high risk" if proba >= 0.5 else ("🟡 watch" if proba >= 0.35 else "🟢 low risk")
        st.write(f"Risk band: **{band}**")
        st.write(f"Tolerance: **{row['tolerance_class']}**  |  Material: **{row['material']}**")
        st.write(f"Category: **{row['part_category']}**  |  Revisions: **{int(row['revision_count'])}**")
        st.write(f"Team: **{row['designer_team']}**  |  Mass: **{row['mass_kg']:.2f} kg**")
        st.write(f"Actual outcome: **{'reworked' if row['reworked'] else 'clean'}** "
                 f"(${row['cost']:,.0f} cost)")
    with c2:
        d = drivers(feat)
        fig = px.bar(d, x="contribution", y="driver", orientation="h", color="contribution",
                     color_continuous_scale="RdYlGn_r", title="What drives this part's risk score")
        fig.update_layout(yaxis={"categoryorder": "total ascending"}, showlegend=False)
        st.plotly_chart(fig, use_container_width=True)
    st.caption(f"Logistic model fitted in the notebook — test ROC-AUC {coefs['auc']}. "
               "Design-time features only, no leakage.")

with tab3:
    pivot = df.groupby(["tolerance_class", "material"])["reworked"].mean().unstack()
    fig = px.imshow(pivot, text_auto=".0%", aspect="auto", color_continuous_scale="Reds",
                    title="Rework rate — tolerance × material",
                    labels={"x": "material", "y": "tolerance", "color": "rework rate"})
    st.plotly_chart(fig, use_container_width=True)
    st.info("The danger zone is **tight tolerance × abs_plastic** — flag that combo at design review.")
    by_cat = df.groupby("part_category")["reworked"].mean().reset_index().sort_values("reworked")
    fig = px.bar(by_cat, x="reworked", y="part_category", orientation="h", color="reworked",
                 color_continuous_scale="Oranges", title="Rework rate by part category",
                 labels={"reworked": "rework rate", "part_category": ""})
    fig.update_layout(showlegend=False, xaxis_tickformat=".0%")
    st.plotly_chart(fig, use_container_width=True)

with tab4:
    st.write("Parts with the most design revisions — churn is a leading indicator of rework.")
    lead = df.sort_values("revision_count", ascending=False).head(20).copy()
    lead["risk"] = lead.apply(lambda r: score_part(r)[0], axis=1)
    show = lead[["part_id", "part_category", "tolerance_class", "material",
                 "revision_count", "designer_team", "risk", "reworked", "cost"]].reset_index(drop=True)
    show.columns = ["Part", "Category", "Tolerance", "Material", "Revisions",
                    "Team", "Risk score", "Reworked", "Cost $"]
    st.dataframe(show.style.format({"Risk score": "{:.0%}", "Cost $": "${:,.0f}"}),
                 use_container_width=True)
